### ISSUE TITLE
初始化从端失败

### ISSUE THREAD

**Issue by 1045925330** [ehForwarderBot/efb-qq-plugin-go-cqhttp#45]
这是efb的日志

2022-08-06 19:51:53,258 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     正在初始化从端 milkice.qq…
Traceback (most recent call last):
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 806, in _coolq_api_wrapper
    res = await self.coolq_bot.call_action(func_name, **kwargs)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 185, in call_action
    result = await self._http_api.call_action(action, **params)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 71, in call_action
    raise HttpFailed(resp.status_code)
aiocqhttp.exceptions.HttpFailed: <HttpFailed, status_code=502>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_slave/ClientMgr.py", line 27, in __init__
    self.client = cls(name, config, channel)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 528, in __init__
    asyncio.run(self.check_status_periodically(run_once=True))
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 845, in check_status_periodically
    flag = await self.check_running_status()
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 822, in check_running_status
    res = await self._coolq_api_wrapper("get_status")
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 812, in _coolq_api_wrapper
    ex.status_code, ex.retcode
AttributeError: 'HttpFailed' object has no attribute 'retcode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xh1045925330/anaconda3/envs/efb/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/home/xh1045925330/anaconda3/envs/efb/lib/python3.8/site-packages/efb_qq_slave/ClientMgr.py", line 30, in __init__
    raise Exception("Specified client not found!")
Exception: Specified client not found!

**Comment by 1045925330** [comment]
这是go-cqhttp的日志

[2022-08-06 18:48:11] [INFO]: 当前版本:v1.0.0-rc3
[2022-08-06 18:48:11] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-08-06 18:48:11] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-08-06 18:48:16] [INFO]: 开始尝试登录并同步消息...
[2022-08-06 18:48:16] [INFO]: 使用协议: iPad
[2022-08-06 18:48:17] [INFO]: Protocol -> connect to server: 157.148.54.170:8080
[2022-08-06 18:48:17] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2022-08-06 18:48:19] [INFO]: 登录成功 欢迎使用: 好耶
[2022-08-06 18:48:19] [INFO]: 开始加载好友列表...
[2022-08-06 18:48:19] [INFO]: 共加载 153 个好友.
[2022-08-06 18:48:19] [INFO]: 开始加载群列表...
[2022-08-06 18:48:21] [INFO]: 共加载 15 个群.
[2022-08-06 18:48:21] [INFO]: 资源初始化完成, 开始处理信息.
[2022-08-06 18:48:21] [INFO]: アトリは、高性能ですから!
[2022-08-06 18:48:21] [INFO]: 正在检查更新.
[2022-08-06 18:48:21] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:8000
[2022-08-06 18:48:21] [INFO]: CQ HTTP 服务器已启动: [::]:5700
[2022-08-06 18:48:21] [WARNING]: 检查更新失败: Get "https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest": dial tcp 127.0.0.1:443: connect: connection refused
[2022-08-06 18:48:21] [INFO]: 开始诊断网络情况
[2022-08-06 18:48:23] [INFO]: 网络诊断完成. 未发现问题
[2022-08-06 18:48:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试
[2022-08-06 18:48:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 2 次重试
[2022-08-06 18:48:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 3 次重试
[2022-08-06 18:48:30] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1659782906,"self_id":1045925330,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":63,"packet_sent":55,"packet_lost":0,"message_received":1,"message_sent":0,"last_message_time":1659782899,"disconnect_times":0,"lost_times":0}},"interval":5000}
 到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 停止上报：已达重试上限
[2022-08-06 18:48:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 1 次重试
[2022-08-06 18:48:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 2 次重试
[2022-08-06 18:48:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 将进行第 3 次重试
[2022-08-06 18:48:35] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1659782911,"self_id":1045925330,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":63,"packet_sent":55,"packet_lost":0,"message_received":1,"message_sent":0,"last_message_time":1659782899,"disconnect_times":0,"lost_times":0}},"interval":5000}
 到 http://127.0.0.1:8000 失败: Post "http://127.0.0.1:8000": dial tcp 127.0.0.1:8000: connect: connection refused 停止上报：已达重试上限

**Comment by 1045925330** [comment]
配置文件如下
milkice.qq：

Client: GoCQHttp                      # 指定要使用的 QQ 客户端（此处为 GoCQHttp）
GoCQHttp:
    type: HTTP                        # 指定 efb-qq-plugin-go-cqhttp 与 GoCQHttp 通信的方式 现阶段仅支持 HTTP
    access_token:
    api_root: http://127.0.0.1:5700/  # GoCQHttp API接口地址/端口
    host: 127.0.0.1                   # efb-qq-slave 所监听的地址用于接收消息
    port: 8000                        # 同上




go-cqhttp：

  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
       - url: 'http://127.0.0.1:8000'                # 地址
         secret: ''             # 密钥
