### ISSUE TITLE
依旧无法接收文件

### ISSUE THREAD

**Issue by phoenixxie0** [ehForwarderBot/efb-qq-plugin-go-cqhttp#47]
2022-07-28 12:33:42,408 [DEBUG]: peewee (peewee.execute_sql; peewee.py:3185)
('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_member_uid", "media_type", "mime", "file_id", "file_unique_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['93189374.62', None, 'offline_file.1658982820', '小号小号(.) uploaded a file to you\nFilename: DSC07323.xmp\nFile size: 8751', 'milkice.qq offline_file', 'milkice.qq system offline_file', 'Text', None, None, None, 'Text', 'blueset.telegram', datetime.datetime(2022, 7, 28, 12, 33, 42, 406179)])
2022-07-28 12:33:42,451 [DEBUG]: efb_telegram_master.db (db.add_or_update_message_log; db.py:420)
[93189374.62] Database insert/update outcome: 1
2022-07-28 12:33:42,455 [DEBUG]: urllib3.connectionpool (connectionpool._new_conn; connectionpool.py:228)
Starting new HTTP connection (1): 14.22.6.247:80
2022-07-28 12:33:42,502 [DEBUG]: urllib3.connectionpool (connectionpool._make_request; connectionpool.py:456)
[http://14.22.6.247:80](http://14.22.6.247/) "GET /ftn_handler/ebce6c4164c601659ae029a5c4141e2bd18e9ac45a53f669ee82f5e62547973f2a60d859cd33de0d03882c3597bd678e72997a9070976e573affb08384b679ee HTTP/1.1" 200 8751
2022-07-28 12:33:42,559 [ERROR]: asyncio (base_events.default_exception_handler; base_events.py:1707)
Task exception was never retrieved
future: <Task finished name='Task-55' coro=<GoCQHttp.init..handle_offline_file_upload_msg.._handle_offline_file_upload_msg() done, defined at /usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py:356> exception=RuntimeError('asyncio.run() cannot be called from a running event loop')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 369, in _handle_offline_file_upload_msg
await self.async_download_file(**param_dict)
File "/usr/local/lib/python3.8/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 1058, in async_download_file
efb_msg.chat = asyncio.run(self.chat_manager.build_efb_chat_as_private(context))
File "/usr/local/lib/python3.8/asyncio/runners.py", line 33, in run
raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/usr/local/lib/python3.8/asyncio/base_events.py:1844: RuntimeWarning: coroutine 'ChatManager.build_efb_chat_as_private' was never awaited
handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-07-28 12:33:45,071 [INFO]: quart.app (init._handle_event; init.py:596)
received event: meta_event.heartbeat
[2022-07-28 12:33:45,071] INFO in init: received event: meta_event.heartbeat
2022-07-28 12:33:45,146 [DEBUG]: telegram.bot (bot.get_updates; bot.py:3068)
No new updates found.

依旧不能接收文件

**Comment by phoenixxie0** [comment]
最新版已解决
