### ISSUE TITLE
收到的语音消息不能正常处理

### ISSUE THREAD

**Issue by xyf2018** [ehForwarderBot/efb-qq-plugin-go-cqhttp#50]
Windows 10下运行EFB+ETM+EQS，当go-cqhttp收到语音消息时，EFB不能正常处理。
以下为错误信息

`2022-09-06 00:01:29,111 [ERROR]: efb_qq_plugin_go_cqhttp.MsgDecorator (MsgDecorator.qq_record_wrapper; MsgDecorator.py:72)
    Failed to download voice
Traceback (most recent call last):
  File "C:\Users\xyf20\AppData\Local\Programs\Python\Python39\lib\site-packages\efb_qq_plugin_go_cqhttp\Utils.py", line 764, in download_voice
    pilk.decode(origin_file.name, pcm_file.name)
OSError: Error: could not open input file 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xyf20\AppData\Local\Programs\Python\Python39\lib\site-packages\efb_qq_plugin_go_cqhttp\MsgDecorator.py", line 63, in qq_record_wrapper
    efb_msg.file = download_voice(data["url"])
  File "C:\Users\xyf20\AppData\Local\Programs\Python\Python39\lib\site-packages\efb_qq_plugin_go_cqhttp\Utils.py", line 773, in download_voice
    audio_file.close()
UnboundLocalError: local variable 'audio_file' referenced before assignment`

同时telegram侧收到如下消息
`(不支持)
[Voice Message] Please check it on your QQ`

但是在Linux上跑EFB时，没有这个问题

**Comment by omg-xtao** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/1749
